-- TYPE
TYPE_CARD = "Card"
TYPE_DECK = "Deck"
TYPE_TILE = "Tile"
TYPE_SCRIPTING = "Scripting"
TYPE_BAG = "Bag"
SPAWN_TYPE_SCRIPTING_TRIGGER = "ScriptingTrigger"

-- COLOR
COLOR_RED = "Red"
COLOR_BLUE = "Blue"
COLOR_YELLOW = "Yellow"
COLOR_PURPLE = "Purple"
COLOR_WHITE = "White"
COLOR_GREY = "Grey"
COLOR_BLACK = "Black"
PLAYER_COLOR_LIST = {COLOR_RED, COLOR_PURPLE, COLOR_BLUE, COLOR_YELLOW}
NON_PLAYER_COLOR_LIST = {COLOR_WHITE, COLOR_GREY, COLOR_BLACK}

-- variant
SCRIPT_VERSION = 2025062801

GAME = {}
